lane :test do
  github_action(
    api_token: "23j54kjhf88f8h38h238829382b9382b392",
    org: "joshdholtz",
    repo: "fastlane-plugin-github_actions",
    match_org: "joshdholtz",
    match_repo: "match-repo-for-fastlane-plugin-github_actions",
    dotenv_paths: ["fastlane/.env.secret", "fastlane/.env.secret2"]
  )
end
