lane :test do
  github_action(
    api_token: "727f877e732818db329436baef4257a136559c6c",
    org: "joshdholtz",
    repo: "fastlane-plugin-github_actions",
    match_org: "joshdholtz",
    match_repo: "match-repo-for-fastlane-plugin-github_actions",
    dotenv_paths: ["fastlane/.env.secret", "fastlane/.env.secret2"]
  )
end
